# Learning Linear Algebra
### Using python, `numpy`, and `matplotlib`

Following the resources provided by this [Jupyter Guide to Linear Algebra](https://bvanderlei.github.io/jupyter-guide-to-linear-algebra/index.html) notebook.

# Introduction

## Using `numpy`

Rendering a matrix using `numpy` is very simple.

The matrix we wish to render with `numpy` is below:

$$
A=\begin{bmatrix}
5 & -1 & 1 & 0 \\
4 & 3 & 12 & -6 \\
\end{bmatrix}

First, import the `numpy` library. We'll call it `np` to make things easier.

In [1]:
import numpy as np

Next let's create the matrix in python using the `np.array` class:

In [2]:
A = np.array([[5, -1, 1, 0], [4, 3, 12, -6]])
print(A)

[[ 5 -1  1  0]
 [ 4  3 12 -6]]


The LaTeX markdown is identical to the printed python output in cell [3].

**Additionally**, we could create the array I want by using the `reshape` function.

In [3]:
B = np.array([5, -1, 1, 0, 4, 3, 12, -6])
print("This is B before reshaping\n", B)

C = B.reshape((2, 4))
print("This is C, or B formed into a new shape\n", C)

This is B before reshaping
 [ 5 -1  1  0  4  3 12 -6]
This is C, or B formed into a new shape
 [[ 5 -1  1  0]
 [ 4  3 12 -6]]


To retain the original information of the matrix, it's usally best to `copy` the array into a new variable that we can make changes to without destroying the original. We can do this likeso:

In [4]:
D = np.copy(A)
print("Here is a duplicate of the A matrix\n", D)

Here is a duplicate of the A matrix
 [[ 5 -1  1  0]
 [ 4  3 12 -6]]


Use the following method to reassign matrix values:

In [5]:
A[0, 2] = 8
print("Altered A matrix\n", A)

Altered A matrix
 [[ 5 -1  8  0]
 [ 4  3 12 -6]]


It's common to create an array with mostly zeros. As an example, we can do this by:

1. Creating an empty 4x4 array
2. Set entries along the main diagonal to 2

### 1. Creating an empty 4x4 array

In [6]:
D = np.zeros((4, 4))
print("Empty 4x4 matrix\n", D)

Empty 4x4 matrix
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Set entries along the main diagonal to 2

In [7]:
for i in range(4):
    D[i, i] = 2

print("Assigned 4x4 matrix\n", D)

Assigned 4x4 matrix
 [[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


## Using the `random.rand` function

A way to test code is by supplying a lot of random input and checking to see if the correct results are produced every time. To produce the random inputs, we'll use the `random` module and the `rand` function with no arguments to produce a number between zero and one.

In [8]:
r = np.random.rand()
print("Random number\n", r)

Random number
 0.5432739233546299


We can create a matrix of random numbers like so:

In [9]:
X = np.random.rand(3, 2)
print("Matrix of random numbers\n", X)

Matrix of random numbers
 [[0.9485253  0.85144437]
 [0.47141143 0.20290383]
 [0.38700746 0.56739908]]


To generate random integers, we can use the `randint` function. If we write `np.random.randint(20)`, we'll get a random number between (and including) 0 and 19, eg:

In [10]:
print("Random integer between 0 and 19\n", np.random.randint(20))

Random integer between 0 and 19
 18
